#pragma once

// Vial
#define VIAL_KEYBOARD_UID {0x2F, 0xA1, 0x20, 0x44, 0xAC, 0xF6, 0xDB, 0x78}
#define VIAL_UNLOCK_COMBO_ROWS { 0,0 }
#define VIAL_UNLOCK_COMBO_COLS { 0,1 }

// Define options
#define DYNAMIC_KEYMAP_LAYER_COUNT 7
#define TAPPING_TERM 230
#define PERMISSIVE_HOLD

// RGB options
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LIMIT_VAL 50
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_RETAIN_VAL
